---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autoscaling.sarabala.io
  resources:
  - smarthorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.sarabala.io
  resources:
  - smarthorizontalpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.sarabala.io
  resources:
  - smarthorizontalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
